version: '3.8'

services:
    backend:
        container_name: emotion-analysis-backend
        build:
            context: ./be
            dockerfile: Dockerfile
        ports:
            - '8000:8000'
        volumes:
            - ./be/src/models:/app/src/models

    frontend:
        container_name: emotion-analysis-frontend
        build:
            context: ./fe
            dockerfile: Dockerfile
        ports:
            - '4004:3000'
        depends_on:
            - backend
